name: developer_panel_app
description: Native app for Corbado developer panel
publish_to: 'none'

version: 1.2.0+25

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  corbado_auth: ^3.4.1
  corbado_frontend_api_client: ^2.0.0
  riverpod: ^2.3.10
  flutter_riverpod: ^2.3.10
  either_dart: ^1.0.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.2
  go_router: ^14.2.7
  flutter_svg: ^2.0.7
  otp_text_field: ^1.1.3

  openapi_generator_annotations: ^5.0.2
  http: ^1.1.0
  data_table_2: ^2.5.8
  overlay_support: ^2.1.0
  package_info_plus: ^8.0.2
  any_link_preview: ^3.0.1
  modal_bottom_sheet: ^3.0.0-pre
  ua_client_hints: ^1.3.1
  win32: 5.5.4
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  openapi_generator: ^5.0.2
  build_runner: ^2.4.12

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#1953FF"
  adaptive_icon_foreground: "assets/logo/corbado_android.png"

  ios: true
  image_path: "assets/logo/corbado_ios.png"
  min_sdk_android: 21
  remove_alpha_ios: true

#dependency_overrides:
#  corbado_auth:
#    path: ../flutter-passkeys/packages/corbado_auth
#  passkeys:
#    path: ../flutter-passkeys/packages/passkeys/passkeys
#  passkeys_android:
#    path: ../flutter-passkeys/packages/passkeys/passkeys_android
#  passkeys_ios:
#    path: ../flutter-passkeys/packages/passkeys/passkeys_ios
#  passkeys_platform_interface:
#    path: ../flutter-passkeys/packages/passkeys/passkeys_platform_interface
#  corbado_frontend_api_client:
#    path: ../flutter-passkeys/packages/corbado_api_client/lib/frontendapi